# Generated by Django 5.0.1 on 2024-02-10 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_categories_options_alter_news_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Созданно в'),
        ),
        migrations.AlterField(
            model_name='news',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 10, 12, 7, 30, 505444), verbose_name='Опубликовать в'),
        ),
    ]
